.\"Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd March 30, 2026
.Dt APPSCRIPT 1
.Os
.Sh NAME
.Nm appscript
.Nd Very lightweight script to create self-extractable archives
.Sh SYNOPSIS
.Nm
.Fl v
.Nm
.Op Fl t
.Op Fl c Oo Cm gzip Ns | Ns Cm xz Ns | Ns Cm zstd Oc
.Op Fl o Ar filename
.Ar directory
.Sh DESCRIPTION
.Nm
is a very lightweight script that compresses a directory using
.Xr tar 1 Ns ,
encodes the result with
.Xr base64 1 ,
and then creates a
.Xr sh 1
script that decompresses that result into a temporary location
.Po optionally using Xr tmpfs 4 Pc Ns , and finally executes a script named
.Sy APPSCRIPT
from the current working directory.
.Pp
The resulting script handles signals generated by certain events to
clean up the temporary location created, including unmounting the mounted
.Xr tmpfs 4
filesystem if the script is configured to do so.
.Pp
The idea is similar to how
.Xr makeself 1
works, but it is written entirely in POSIX shell, leveraging
.Xr tmpfs 4 Ns ,
and is much lighter.
.Nm
has been implemented in fewer than 160 lines, and the resulting script
has fewer than 60 lines. Unlike
.Xr makeself 1 Ns ,
which aims to implement more use cases and emulate the behavior of some
file archiving utilities that create executables,
.Nm
only aims to run a script with all dependencies contained within it. In this context,
.Dq dependencies
refers to the files the script wants to use. You can combine
.Nm
with
.Xr appjail 1
to run applications
.Pq possibly with Xr appjail-x11 1
in an isolated and disposable manner. From the user’s perspective, it’s
like running an application with a single click.
.Pp
.Bl -tag -width xxx
.It Fl v
Display version information about
.Nm Ns .
.It Fl t
Configure the resulting script to use
.Xr tmpfs 4
when
.Sy vfs.usermount
is set to
.Sy 1 Ns "."
If the attempt to mount
.Xr tmpfs 4
fails, the resulting script will continue regardless.
.It Fl c Oo Cm gzip Ns | Ns Cm xz Ns | Ns Cm zstd Oc
Compression algorithm to be used.
.Sy xz
is the default.
.It Fl o Ar filename
Name of the resulting script. By default,
.Sy /dev/stdout Ns "."
.Pp
The execute bit is always set if this argument is a file.
.It Ar directory
Directory to be compressed.
.Pp
.Nm
assumes that the
.Sy APPSCRIPT
script is already present and has the execute bit set.
.El
.Sh ENVIRONMENT
.Bl -tag -width xxx
.It Ev APPSCRIPT_PWD
Since
.Sy APPSCRIPT
runs from the current user's working directory, it does not know the
location of the temporary directory. This environment variable
specifies that location.
.It Ev APPSCRIPT_SCRIPT
Absolute path to the AppScript that is currently running.
.El
.Sh SEE ALSO
.Xr appjail 1
.Xr tar 1
.Xr base64 1
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
