.\"Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd April 6, 2026
.Dt APPSCRIPT 1
.Os
.Sh NAME
.Nm appscript
.Nd Simple, lightweight and effective tool for creating SFX files
.Sh SYNOPSIS
.Nm
.Fl v
.Nm
.Op Fl L
.Op Fl c Oo Cm gzip Ns | Ns Cm xz Ns | Ns Cm zstd Oc
.Op Fl o Ar filename
.Ar directory
.Sh DESCRIPTION
.Nm
is a very lightweight and easy-to-use tool for creating self-extracting executables.
.Pp
From the developer's perspective,
.Xr tar 1
is used to compress a directory into a tarball, known as the
.Dq payload,
which is stored in the .rodata section,
.Xr objcopy 1
to convert the payload into a valid
.Xr elf 3 object file, and then
.Xr clang 1
to compile the payload with the C-written stub. And from the user's
perspective, it just need to run the executable file, and the magic
happens behind the scenes: the AppScript
.Pq the SFX file
reads the addresses where the payload is located and uses
.Xr libarchive 3
to extract the files to a temporary directory, finally executing an executable file named
.Sy APPSCRIPT Ns "."
The user can pass any environment variables and arguments to the AppScript, and the
.Sy APPSCRIPT
executable can handle them just like any other program or script.
.Pp
However, an AppScript does much more than what has been described above. First,
it sets handlers for
.Em SIGHUP Ns , Em SIGINT Ns , Em SIGQUIT Ns , Em SIGTERM Ns , Em SIGXCPU Ns , and Em SIGXFSZ
to stop the AppScript when it's running.
.Em SIGALRM Ns , Em SIGVTALRM Ns , Em SIGPROF Ns , Em SIGUSR1 Ns , and Em SIGUSR2
are ignored. Next, it checks if the
.Pa /var/tmp/appscript
directory exists and, if so, uses it to create temporary directories; otherwise,
.Pa /tmp
is used as fallback. The reason
.Pa /var/tmp/appscript
is preferred is that a system administrator can configure this location
to mount a
.Xr tmpfs 4
filesystem to improve the performance of very large AppScripts. This is
more secure than setting
.Dq vfs.usermount=1
and letting the user
.Pq or, in this case, the user's process
mount a
.Xr tmpfs 4
filesystem. Regardless of the directory used, it must have file mode 1777; otherwise, an
.Sy EX_NOPERM
error will be returned. After initial checks, the tarball is extracted
to a temporary location determined by the directories mentioned above.
The AppScript will refuse to extract absolute paths and entries
containing periods, and will apply basic protection against symbolic
links
.Po see ARCHIVE_EXTRACT_SECURE_SYMLINKS in Xr archive_write_disk 3 No for details Pc Ns "."
Finally, if no signal is received and no errors are detected during the
files extraction, the AppScript will attempt to execute the
.Sy APPSCRIPT
file. For this to succeed, the file must have the execute bit set
and the owner must be the same as the effective uid, which should be
the case since the uid and gid are changed to the caller when the files
are extracted. As a final task, the temporary directory is recursively
removed in a similar way to the
.Fl r
and
.Fl f
flags in
.Xr rm 1 Ns "."
.Pp
.Bl -tag -width xxx
.It Fl L
All symbolic links will be followed.
.br
Normally, symbolic links are archived as such. With this option, the
target of the link will be archived instead.
.It Fl v
Display version information about
.Nm Ns .
.It Fl o Ar filename
Name of the resulting executable. By default,
.Sy a.AppScript Ns "."
.It Ar directory
Directory to be compressed.
.Pp
.Nm
assumes that the
.Sy APPSCRIPT
script is already present and has the execute bit set.
.El
.Sh ENVIRONMENT
.Bl -tag -width xxx
.It Ev APPSCRIPT_PWD
Since
.Sy APPSCRIPT
runs from the current user's working directory, it does not know the
location of the temporary directory. This environment variable
specifies that location.
.It Ev APPSCRIPT_SCRIPT
Absolute path to the AppScript that is currently running.
.El
.Sh EXAMPLES
.Ss Improving performance
If you are the sovereign of your system, users will appreciate you if you enable
.Xr tmpfs 4
at
.Pa /var/tmp/appscript
for very large AppScripts:
.Bd -literal -offset indent
# /etc/fstab
tmpfs   /var/tmp/appscript  tmpfs   rw,size=1G,mode=1777,late  0   0
.Ed
.Pp
Then:
.Bd -literal -offset indent
# mkdir -p /var/tmp/appscript
# mount /var/tmp/appscript
.Ed
.Ss The Do Hello World Dc example
To create the most basic AppScript all you have to do is create a directory:
.Bd -literal -offset indent
$ mkdir hello-world
.Ed
.Pp
Create the
.Sy APPSCRIPT
file:
.Bd -literal -offset indent
$ cat << EOF > \&./hello-world/APPSCRIPT
#!/bin/sh

echo "Hello, world!"
EOF
.Ed
.Pp
And set the execute bit:
.Bd -literal -offset indent
$ chmod +x \&./hello-world/APPSCRIPT
.Ed
.Pp
To finally create the AppScript:
.Bd -literal -offset indent
$ appscript \&./hello-world
$ ls
\&./a.AppScript
$ \&./a.AppScript
Hello, world!
.Ed
.Sh SEE ALSO
.Xr tar 1
.Xr libarchive 3
.Xr signal 3
.Xr sysexits 3
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
